### ISSUE TITLE
Provider plugin fails when ansible not installed

### ISSUE THREAD

**Issue by stevestrutt** [ansible/terraform-provider-ansible#35]
Terraform provider plugin fails and does not return messages when ansible-playbook is not found in local path (not installed) 

`exec: "ansible-playbook": executable file not found in $PATH` 

![image](https://github.com/ansible/terraform-provider-ansible/assets/15387195/fdf2e6fb-a193-4da8-bd65-dfa33f077c21)

**Comment by gravesm** [comment]
@stevestrutt this provider does not install ansible for you. You will have to make sure it is installed. You can also set the location of path using https://registry.terraform.io/providers/ansible/ansible/latest/docs/resources/playbook#ansible_playbook_binary.

**Comment by stevestrutt** [comment]
@gravesm Agreed Ansible needs to be installed first. The issue is that the error reported to the user if it is not installed is an obscure plugin failure message.  

I think this is more of a generic issue for the provider that a failure did not return the cmd exec messages to indicate the cause of the problem. Debugging the issue required that the user is a knowledgeable provider developer and knows to set the TF_PROVIDER_LOG to get the messages to determine the issue.

**Comment by techieforfun** [comment]
Is there an option to embed the `ansible` binaries within the provider? When using this provider with Terraform Cloud workers, installing Ansible is not possible due to the lack of root access on the runner.
