### ISSUE TITLE
Possible race condition between multiple ansible_playbook resources?

### ISSUE THREAD

**Issue by yann-soubeyrand** [ansible/terraform-provider-ansible#38]
Hello,

I read the code of the `ansible_playbook` resource and I don’t understand this line:
https://github.com/ansible/terraform-provider-ansible/blob/c3f22e32972f1c5838b0fe250e90e045cb7c1ef6/provider/resource_playbook.go#L474
Why can’t we just use the `tempInventoryFile` variable? Also, doesn’t it open the door to race conditions between multiple `ansible_playbook` (taking into account inventory files of each others)?

**Comment by fbjerggaard** [comment]
It is definitely an issue - I have encountered issues when running against multiple terraform hosts at the same time because they all access all inventory files.

My fix was to use a local development version of the provider without the GetAllInventories code, and it works much better.
