### ISSUE TITLE
ansible_playbook resource is recreated every time if using replayable=true

### ISSUE THREAD

**Issue by santimar** [ansible/terraform-provider-ansible#81]
I can't fully grasp the logic behind `redeployable = true` at the moment, that just recreates the resource every time.

I was expecting that on the second `terraform apply`, the playbook would run in `check-mode` and only if ansible reports that changes needs to be made, the `ansible_playbook` resource would be recreated.

At the moment though, the `ansible_playbook` is always recreated whether changes needs to be made or not.

This will partially defeat Terraform goal, since under normal circumstances if no change is needed, no resource should be modified.
Also, it produce noise on Terraform logs, making harder to read other resources changes.

Is there a reason why this approach is not followed?

**Comment by ralgar** [comment]
This is a duplicate of #77. I wholeheartedly agree though.

**Comment by santimar** [comment]
Yes, I missed the other issue.
Closing since it's duplicated
