### ISSUE TITLE
Add signature validation

### ISSUE THREAD

**Issue by willifehler** [ansible/terraform-provider-ansible#93]
Hey there,

there is a warning if I install this provider:

`
Installed ansible/ansible v1.1.0. Signature validation was skipped due to the registry not containing GPG keys for this provider
`

It would be nice to add gpg validation.

Cheers - Willi

**Comment by gravesm** [comment]
@willifehler This is not something I can reproduce. In fact, signing [is required](https://developer.hashicorp.com/terraform/registry/providers/publishing#preparing-and-adding-a-signing-key) in order to publish a new release. Is this still something you are having a problem with?

**Comment by willifehler** [comment]
Hi @gravesm,

I can't reproduce the issue. I will close this request now.

Cheers - Willi
